[project]
name = "pac-man"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flake8>=7.4.1",
    "mazegenerator",
    "mypy>=2.4.0",
    "pydantic>=2.13.5",
    "pygame>=2.6.1",
]

[tool.uv.sources]
mazegenerator = { path = "mazegenerator-2.1.0-py3-none-any.whl" }

[[tool.mypy.overrides]]
module = "mazegenerator.*"
ignore_missing_imports = true
